apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: wildfowl-nodejs 
  janus-idp.io/tekton: wildfowl-nodejs
  backstage.io/kubernetes-id: wildfowl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wildfowl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  